name: Build ARM JSON from Bicep


on: 
  push:
    branches:
      - main
    
jobs:
  build-bicep:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Bicep Build
        uses: Azure/bicep-build-action@c333f970fb0daae2241062b5b7acf30a97f696c9 # v1.0.0
        with:
          bicepFilePath: ctfd.bicep
          outputFilePath: azuredeploy.json
      - uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
