name: Build ARM from Bicep


on: 
  workflow_dispatch:
#  workflow_dispatch:
#  push:
#    branches:
#      - master
    
jobs:
  build-bicep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Bicep Build
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: ctfd.bicep
          outputFilePath: azuredeploy.json
      - uses: stefanzweifel/git-auto-commit-action@v4
